const DocumentType = {
    MATERIAL_EFFECT: 'MATERIAL_EFFECT',
    PRESCRIPTIVE_DOCUMENT: 'PRESCRIPTIVE_DOCUMENT',
    DESIGN_DOCUMENT: 'DESIGN_DOCUMENT',
    TECHNICAL_DOCUMENT: 'TECHNICAL_DOCUMENT',
    INFORMATIVE_DOCUMENT: 'INFORMATIVE_DOCUMENT'
};

Object.freeze(DocumentType)
export default DocumentType;